import {
  defineMetabaseAuthConfig,
  MetabaseProvider,
  defineMetabaseTheme,
} from "@metabase/embedding-sdk-react/nextjs";
import type { Metadata } from "next";

import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

if (!process.env.NEXT_PUBLIC_METABASE_INSTANCE_URL) {
  throw new Error("Missing NEXT_PUBLIC_METABASE_INSTANCE_URL");
}

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const authConfig = defineMetabaseAuthConfig({
  metabaseInstanceUrl: process.env.NEXT_PUBLIC_METABASE_INSTANCE_URL,
  authProviderUri: `/api/metabase/auth`,
});

const theme = defineMetabaseTheme({
  // Specify a font to use from the set of fonts supported by Metabase.
  // You can set the font to "Custom" to use the custom font
  // configured in your Metabase instance.
  fontFamily: "Lato",

  // Override the base font size for every component.
  // This does not usually need to be set, as the components
  // inherit the font size from the parent container, such as the body.
  fontSize: "16px",

  // Override the base line height for every component.
  lineHeight: 1.5,

  // Match your application's color scheme
  colors: {
    brand: "#6b88bd",
    "text-primary": "#FFFFFF",
    "text-secondary": "#B0BEC5",
    "text-tertiary": "#78909C",
    background: "#181A1B",
    "background-hover": "#23272B",
    border: "#263238",
    filter: "#939393",
    summarize: "#5e749c",
    shadow: "rgba(0,0,0,0.6)",
  },

  components: {
    question: {
      backgroundColor: "#23272B",
    },
    table: {
      cell: {
        textColor: "#FFFFFF",
        backgroundColor: "#181A1B",
      },
    },
  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ display: "flex" }}
      >
        <nav>
          <Link href="/">
            <strong>Nextjs App Router</strong>
          </Link>
          <Link href="/static-question">Static question </Link>
          <Link href="/interactive-question">Interactive question</Link>
          <Link href="/static-dashboard">Static Dashboard</Link>
          <Link href="/interactive-dashboard">Interactive Dashboard</Link>
        </nav>
        <MetabaseProvider authConfig={authConfig} theme={theme}>{children}</MetabaseProvider>
      </body>
    </html>
  );
}
